export enum EntityType {
  ENTERPRISE = 'ENTERPRISE',
  PERSON = 'PERSON',
  DRUG = 'DRUG',
  SYMPTOM = 'SYMPTOM',
  DISEASE = 'DISEASE',
  LOCATION = 'LOCATION',
  ORGANIZATION = 'ORGANIZATION',
  PRODUCT = 'PRODUCT',
  EVENT = 'EVENT',
}
