export enum Industry {
  FINANCE = 'FINANCE',
  HEALTHCARE = 'HEALTHCARE',
  TECHNOLOGY = 'TECHNOLOGY',
  RETAIL = 'RETAIL',
  MANUFACTURING = 'MANUFACTURING',
  ENERGY = 'ENERGY',
  TRANSPORTATION = 'TRANSPORTATION',
}
