export enum RelationType {
  HOLDS_STOCK = 'HOLDS_STOCK',
  GUARANTEES = 'GUARANTEES',
  TREATS = 'TREATS',
  CAUSES = 'CAUSES',
  ASSOCIATED_WITH = 'ASSOCIATED_WITH',
  WORKS_FOR = 'WORKS_FOR',
  LOCATED_IN = 'LOCATED_IN',
  OWNS = 'OWNS',
  PART_OF = 'PART_OF',
  RELATED_TO = 'RELATED_TO',
}
